# Generated by Django 5.1.3 on 2025-07-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
