# Generated by Django 5.2.4 on 2025-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0003_transaction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='debtor_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
