# Generated by Django 5.2.4 on 2025-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0005_transaction_deleted_at_transaction_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
