# Generated by Django 5.2.4 on 2025-07-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0007_casedetails_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetails',
            name='interest_Rate',
        ),
    ]
