# Generated by Django 5.2.4 on 2025-07-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0008_remove_casedetails_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='judgment_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
