# Generated by Django 5.2.4 on 2025-07-25 06:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0009_alter_casedetails_judgment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='total_payments',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
    ]
