# Generated by Django 5.2.4 on 2025-07-25 06:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0011_alter_casedetails_accrued_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='principal_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
    ]
