# Generated by Django 5.2.4 on 2025-07-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0012_alter_transaction_accrued_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, help_text='Annual interest rate (%)', max_digits=6),
        ),
    ]
