# Generated by Django 5.2.4 on 2025-08-02 12:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0013_alter_casedetails_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='principal_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
    ]
