# Generated by Django 5.2.4 on 2025-08-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0014_casedetails_principal_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetails',
            name='principal_balance',
        ),
    ]
