# Generated by Django 5.2.4 on 2025-08-02 19:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0015_remove_casedetails_principal_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='today_payoff',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
    ]
