# Generated by Django 5.2.4 on 2025-08-03 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0016_casedetails_today_payoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='show_principal_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12),
        ),
    ]
