# Generated by Django 5.2.4 on 2025-08-03 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0017_transaction_show_principal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='interest_rate',
            field=models.DecimalField(decimal_places=6, help_text='Annual interest rate (%)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='judgment_amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='payoff_amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='today_payoff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='total_payments',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='principal_balance',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='show_principal_balance',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
    ]
