# Generated by Django 5.2.4 on 2025-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0018_alter_casedetails_accrued_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='judgment_amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
