# Generated by Django 5.2.4 on 2025-08-14 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0019_alter_casedetails_judgment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='payoff_amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='today_payoff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='total_payments',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=30),
        ),
    ]
