# Generated by Django 5.2.4 on 2025-08-14 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0020_alter_casedetails_accrued_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='judgment_amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='payoff_amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='today_payoff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='total_payments',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
    ]
