# Generated by Django 5.1.3 on 2025-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_tasks',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
