# Generated by Django 5.2.4 on 2025-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_specialties_remove_user_tasks_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
